/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MainFrame2.java
 *
 * Created on 6 juin 2012, 16:03:07
 */
package wekabayesnetwork;

import java.awt.TextArea;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JTextArea;
import wekabayesnetwork.Options.BNLearningOptions;
import wekabayesnetwork.Options.ClusteringLearninigOptions;
import wekabayesnetwork.Options.TestingOptionsList;
import wekabayesnetwork.Options.TrainingOptions;

/**
 *
 * @author akram
 */
public class MainFrame extends javax.swing.JFrame
{

    /**
     * Creates new form MainFrame2
     */
    public MainFrame()
    {
        initComponents();

        //test
        this.nomProjetTextField.setText("g");
        this.cheminCorpus1TextField.setText("/home/akram/Bureau/ncf.fr");
        this.cheminCorpus2TextField.setText("/home/akram/Bureau/ncf.en");
        this.cheminTextTestTextField.setText(
                "/home/akram/Bureau/nc-test2007f.fr");
        this.cheminTextRefTextField.setText("/home/akram/Bureau/nc-test2007f.en");
        //

        this.metriqueCoucheInter1ComboBox.setEnabled(false);
        this.metriqueCoucheInter2ComboBox.setEnabled(false);
        //
        this.freqMinTestCheckBox.setEnabled(false);
        this.freqMaxTestCheckBox.setEnabled(false);
        //
        this.freqMinApprentissageCheckBox.setEnabled(false);
        this.freqMaxApprentissageCheckBox.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        nomProjetTextField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        phaseApprentissageCheckBox = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        langue2ComboBox = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        cheminCorpus2TextField = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        delim1TextField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        cheminCorpus1TextField = new javax.swing.JTextField();
        langue1ComboBox = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        delim2TextField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        freqMinApprentissageCheckBox = new javax.swing.JTextField();
        normaliseDelimApprentissageCheckBox = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        freqMaxApprentissageCheckBox = new javax.swing.JTextField();
        suppMotsNonAlphaApprentissageCheckBox = new javax.swing.JCheckBox();
        textminisculeApprentissageCheckBox = new javax.swing.JCheckBox();
        tokeniserApprentissageCheckBox = new javax.swing.JCheckBox();
        ligneUniqApprentissageCheckBox = new javax.swing.JCheckBox();
        stemmersApprentissageCheckBox = new javax.swing.JCheckBox();
        suppMotsOutilsApprentissageCheckBox = new javax.swing.JCheckBox();
        nettoyageApprentissageCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        phrasesMaxAppretissageTextField = new javax.swing.JTextField();
        phrasesMinAppretissageTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        frequenceApprentissageCheckBox = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        nombreConceptsMoyTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        conceptsStemmersCheckBox = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        metriqueCoucheInter1ComboBox = new javax.swing.JComboBox();
        metriqueCoucheInter2ComboBox = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        utiliserCouchesInterCheckBox = new javax.swing.JCheckBox();
        coucheBinaireCheckBox = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nombreMotsMaxConceptTextField = new javax.swing.JTextField();
        metrique2ComboBox = new javax.swing.JComboBox();
        metrique1ComboBox = new javax.swing.JComboBox();
        jButton4 = new javax.swing.JButton();
        cheminConceptRef2TextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        cheminConceptRef1TextField = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        methodeClassifComboBox = new javax.swing.JComboBox();
        distanceClassifComboBox = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        parentsMaxRBTextField = new javax.swing.JTextField();
        suppArcsIndexeCheckBox = new javax.swing.JCheckBox();
        classeIndexeRBTextField = new javax.swing.JTextField();
        scoreRBComboBox = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        structRBComboBox = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cheminTextTestTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        cheminTextRefTextField = new javax.swing.JTextField();
        suppMotsInconnusTestCheckBox = new javax.swing.JCheckBox();
        phraseDelimTestCheckBox = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        stemmersTestCheckBox = new javax.swing.JCheckBox();
        ligneUniqTestCheckBox = new javax.swing.JCheckBox();
        phrasesMaxTestTextField = new javax.swing.JTextField();
        phrasesMinTestTextField = new javax.swing.JTextField();
        freqMaxTestCheckBox = new javax.swing.JTextField();
        normaliseDelimTestCheckBox = new javax.swing.JCheckBox();
        frequenceTestCheckBox = new javax.swing.JCheckBox();
        suppMotsNonAlphaTestCheckBox = new javax.swing.JCheckBox();
        tokeniserTestCheckBox = new javax.swing.JCheckBox();
        freqMinTestCheckBox = new javax.swing.JTextField();
        suppMotsOutilsTestCheckBox = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        textminisculeTestCheckBox = new javax.swing.JCheckBox();
        nettoyageTestCheckBox = new javax.swing.JCheckBox();
        jLabel25 = new javax.swing.JLabel();
        alphaRBTextField = new javax.swing.JTextField();
        setEvidenceRBCheckBox = new javax.swing.JCheckBox();
        chercheTousMotsRBCheckBox = new javax.swing.JCheckBox();
        evidenceEquiRBCheckBox = new javax.swing.JCheckBox();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        utiliserRBCheckBox = new javax.swing.JCheckBox();
        modeleIbmComboBox = new javax.swing.JComboBox();
        executerButton = new javax.swing.JButton();
        utiliserMosesCheckBox = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel24.setText("Nom du projet");

        phaseApprentissageCheckBox.setSelected(true);
        phaseApprentissageCheckBox.setText("Phase d'apprentissage");

        jLabel2.setText("Choix du corpus bi-langue:");

        langue2ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "fr", "en", "es" }));
        langue2ComboBox.setSelectedIndex(1);

        jLabel35.setText("Langue 2:");

        jButton7.setText("...");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel34.setText("Chemin corpus 2:");

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        delim1TextField.setText(" +");

        jLabel33.setText("Délimiteur 1:");

        langue1ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "fr", "en", "es" }));

        jLabel32.setText("Langue 1:");

        jButton6.setText("...");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel31.setText("Chemin corpus 1:");

        jLabel36.setText("Délimiteur 2:");

        delim2TextField.setText(" +");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phaseApprentissageCheckBox)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel32)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(langue1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cheminCorpus1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delim1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(langue2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cheminCorpus2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel36)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(delim2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomProjetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(286, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(phaseApprentissageCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(nomProjetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(jButton7)
                            .addComponent(cheminCorpus2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(langue2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(delim2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel31)
                                .addComponent(jButton6)
                                .addComponent(cheminCorpus1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel32)
                                .addComponent(langue1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(7, 7, 7)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel33)
                                .addComponent(delim1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(242, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Données", jPanel1);

        normaliseDelimApprentissageCheckBox.setSelected(true);
        normaliseDelimApprentissageCheckBox.setText("Normaliser délimiteur");

        jLabel13.setText("Min:");

        suppMotsNonAlphaApprentissageCheckBox.setSelected(true);
        suppMotsNonAlphaApprentissageCheckBox.setText("Supprimer mots incorrects");

        textminisculeApprentissageCheckBox.setSelected(true);
        textminisculeApprentissageCheckBox.setText("Texte en miniscule");

        tokeniserApprentissageCheckBox.setSelected(true);
        tokeniserApprentissageCheckBox.setText("Tokeniser");

        ligneUniqApprentissageCheckBox.setSelected(true);
        ligneUniqApprentissageCheckBox.setText("Seule une occurence d'un mot dans une phrase");

        stemmersApprentissageCheckBox.setText("Stemmers");

        suppMotsOutilsApprentissageCheckBox.setSelected(true);
        suppMotsOutilsApprentissageCheckBox.setText("Supprimer mots outils");

        nettoyageApprentissageCheckBox.setSelected(true);
        nettoyageApprentissageCheckBox.setText("Nettoyage:");

        jLabel1.setText("Traitement du corpus bi-langue:");

        phrasesMaxAppretissageTextField.setText("100");

        phrasesMinAppretissageTextField.setText("1");

        jLabel12.setText("Max:");

        jLabel3.setText("Phrases min:");

        frequenceApprentissageCheckBox.setText("Fréquence mots:");

        jLabel4.setText("Phrases max:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(suppMotsOutilsApprentissageCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stemmersApprentissageCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ligneUniqApprentissageCheckBox))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(frequenceApprentissageCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(6, 6, 6)
                                .addComponent(freqMinApprentissageCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(freqMaxApprentissageCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nettoyageApprentissageCheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(6, 6, 6)
                                .addComponent(phrasesMinAppretissageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phrasesMaxAppretissageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(normaliseDelimApprentissageCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textminisculeApprentissageCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tokeniserApprentissageCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(suppMotsNonAlphaApprentissageCheckBox)))))
                .addContainerGap(476, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nettoyageApprentissageCheckBox)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(phrasesMaxAppretissageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phrasesMinAppretissageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frequenceApprentissageCheckBox)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(freqMaxApprentissageCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(freqMinApprentissageCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(normaliseDelimApprentissageCheckBox)
                    .addComponent(textminisculeApprentissageCheckBox)
                    .addComponent(tokeniserApprentissageCheckBox)
                    .addComponent(suppMotsNonAlphaApprentissageCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suppMotsOutilsApprentissageCheckBox)
                    .addComponent(stemmersApprentissageCheckBox)
                    .addComponent(ligneUniqApprentissageCheckBox))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nettoyage", jPanel2);

        jLabel6.setText("Nombre moyen de mots dans les concepts:");

        nombreConceptsMoyTextField.setText("1");

        jLabel5.setText("Critères de classification de mots:");

        conceptsStemmersCheckBox.setText("Stemmers");

        jLabel19.setText("Métrique couche 1:");

        metriqueCoucheInter1ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "word", "imm", "dkl", "entropie" }));

        metriqueCoucheInter2ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "word", "imm", "dkl", "entropie" }));

        jLabel18.setText("Métrique couche 2:");

        utiliserCouchesInterCheckBox.setText("Utiliser des couches intérmidiaires:");
        utiliserCouchesInterCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utiliserCouchesInterCheckBoxActionPerformed(evt);
            }
        });

        coucheBinaireCheckBox.setText("Dernière couche est binaire");

        jLabel16.setText("Concept réference corpus 1:");

        jLabel15.setText("Métrique corpus 2:");

        jLabel14.setText("Métrique corpus 1:");

        nombreMotsMaxConceptTextField.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        nombreMotsMaxConceptTextField.setText("0");

        metrique2ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "word", "imm", "dkl", "entropie" }));

        metrique1ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "word", "imm", "dkl", "entropie" }));

        jButton4.setText("jButton1");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel17.setText("Concept réference corpus 2:");

        jButton5.setText("jButton1");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel37.setText("Méthode de classification:");

        methodeClassifComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SimpleKMeans", "XMeans", "HierarchicalClusterer", "EM", "FarthestFirst", "sIB" }));

        distanceClassifComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EuclideanDistance", "ManhattanDistance" }));

        jLabel38.setText("Distance de classification:");

        jLabel39.setText("Nombre de mots max (>1)");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(metrique2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(metrique1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(28, 28, 28)
                                .addComponent(coucheBinaireCheckBox))
                            .addComponent(utiliserCouchesInterCheckBox)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(methodeClassifComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel18)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(metriqueCoucheInter2ComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(metriqueCoucheInter1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(distanceClassifComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cheminConceptRef1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cheminConceptRef2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreConceptsMoyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel39)
                                        .addGap(18, 18, 18)
                                        .addComponent(nombreMotsMaxConceptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(conceptsStemmersCheckBox))))))
                .addGap(589, 589, 589))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(metrique1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(metrique2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(coucheBinaireCheckBox)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(utiliserCouchesInterCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(metriqueCoucheInter1ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(metriqueCoucheInter2ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(methodeClassifComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(distanceClassifComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cheminConceptRef1TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheminConceptRef2TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nombreConceptsMoyTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(nombreMotsMaxConceptTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(conceptsStemmersCheckBox)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Classification", jPanel3);

        jLabel7.setText("Critères d'apprentissage des réseaux bayésiens:");

        jLabel23.setText("Classe indexe:");

        parentsMaxRBTextField.setText("2");

        suppArcsIndexeCheckBox.setSelected(true);
        suppArcsIndexeCheckBox.setText("Supprimer arcs sortants du classe indexe");

        classeIndexeRBTextField.setText("-1");

        scoreRBComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BAYES", "MDL", "AIC" }));

        jLabel22.setText("Parents Max:");

        structRBComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "K2", "TabuSearch", "HillClimber", "TAN", "SimulatedAnnealing" }));

        jLabel21.setText("Score:");

        jLabel20.setText("Structure:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(structRBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addGap(12, 12, 12)
                                .addComponent(scoreRBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(parentsMaxRBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(classeIndexeRBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(suppArcsIndexeCheckBox)))))
                .addContainerGap(558, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(structRBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(scoreRBComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(parentsMaxRBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(classeIndexeRBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suppArcsIndexeCheckBox))
                .addContainerGap(347, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Réseau bayésien", jPanel4);

        jLabel9.setText("Critères de test:");

        jLabel10.setText("Texte à traduire:");

        jLabel11.setText("Texte d'évaluation:");

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton1");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        suppMotsInconnusTestCheckBox.setSelected(true);
        suppMotsInconnusTestCheckBox.setText("Supprimer mots inconnus");

        phraseDelimTestCheckBox.setText("Délimiteur phrases");

        jLabel30.setText("Phrases max:");

        stemmersTestCheckBox.setText("Stemmers");

        ligneUniqTestCheckBox.setSelected(true);
        ligneUniqTestCheckBox.setText("Seule une occurence d'un mot dans une phrase");

        phrasesMaxTestTextField.setText("100");

        phrasesMinTestTextField.setText("1");

        normaliseDelimTestCheckBox.setSelected(true);
        normaliseDelimTestCheckBox.setText("Normaliser délimiteur");

        frequenceTestCheckBox.setText("Fréquence mots:");

        suppMotsNonAlphaTestCheckBox.setSelected(true);
        suppMotsNonAlphaTestCheckBox.setText("Supprimer mots incorrects");

        tokeniserTestCheckBox.setSelected(true);
        tokeniserTestCheckBox.setText("Tokeniser");

        suppMotsOutilsTestCheckBox.setSelected(true);
        suppMotsOutilsTestCheckBox.setText("Supprimer mots outils");

        jLabel28.setText("Traitement du corpus bi-langue:");

        jLabel29.setText("Phrases min:");

        textminisculeTestCheckBox.setSelected(true);
        textminisculeTestCheckBox.setText("Texte en miniscule");

        nettoyageTestCheckBox.setSelected(true);
        nettoyageTestCheckBox.setText("Nettoyage:");

        jLabel25.setText("Alpha:");

        alphaRBTextField.setText("0");

        setEvidenceRBCheckBox.setText("Tout mettre en évidence");

        chercheTousMotsRBCheckBox.setSelected(true);
        chercheTousMotsRBCheckBox.setText("Recherche dans tous les nœuds");

        evidenceEquiRBCheckBox.setText("Evidence equiprobable");

        jLabel26.setText("Max:");

        jLabel27.setText("Min:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(4, 4, 4)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cheminTextTestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cheminTextRefTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel28)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(frequenceTestCheckBox)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel27)
                                        .addGap(6, 6, 6)
                                        .addComponent(freqMinTestCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(freqMaxTestCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(nettoyageTestCheckBox)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel29)
                                        .addGap(6, 6, 6)
                                        .addComponent(phrasesMinTestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel30)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phrasesMaxTestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(normaliseDelimTestCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textminisculeTestCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tokeniserTestCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(suppMotsNonAlphaTestCheckBox))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(suppMotsInconnusTestCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(phraseDelimTestCheckBox))
                                    .addGroup(jPanel5Layout.createSequentialGroup()
                                        .addComponent(suppMotsOutilsTestCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(stemmersTestCheckBox)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ligneUniqTestCheckBox))))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(alphaRBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(setEvidenceRBCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chercheTousMotsRBCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(evidenceEquiRBCheckBox))))
                    .addComponent(jLabel9))
                .addContainerGap(373, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheminTextTestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheminTextRefTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nettoyageTestCheckBox)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30)
                    .addComponent(phrasesMaxTestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phrasesMinTestTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frequenceTestCheckBox)
                    .addComponent(jLabel27)
                    .addComponent(jLabel26)
                    .addComponent(freqMaxTestCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(freqMinTestCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(normaliseDelimTestCheckBox)
                    .addComponent(textminisculeTestCheckBox)
                    .addComponent(tokeniserTestCheckBox)
                    .addComponent(suppMotsNonAlphaTestCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suppMotsOutilsTestCheckBox)
                    .addComponent(stemmersTestCheckBox)
                    .addComponent(ligneUniqTestCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(suppMotsInconnusTestCheckBox)
                    .addComponent(phraseDelimTestCheckBox))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(alphaRBTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setEvidenceRBCheckBox)
                    .addComponent(chercheTousMotsRBCheckBox)
                    .addComponent(evidenceEquiRBCheckBox))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Test", jPanel5);

        jLabel8.setText("Modèle IBM utilisé:");

        utiliserRBCheckBox.setSelected(true);
        utiliserRBCheckBox.setText("Utiliser les réseaux bayésiens pour la traduction");

        modeleIbmComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "hmm" }));

        executerButton.setText("Exécuter");
        executerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executerButtonActionPerformed(evt);
            }
        });

        utiliserMosesCheckBox.setText("Utiliser les modèles de traduction IBM (Moses):");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(utiliserRBCheckBox))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modeleIbmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(utiliserMosesCheckBox)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(executerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(utiliserRBCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(utiliserMosesCheckBox)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(modeleIbmComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(executerButton)
                .addContainerGap(293, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Exécution", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1163, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        JFileChooser c = new JFileChooser();
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            String text = (c.getSelectedFile().getAbsolutePath());
            this.cheminCorpus1TextField.setText(text);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        JFileChooser c = new JFileChooser();
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            String text = (c.getSelectedFile().getAbsolutePath());
            this.cheminCorpus2TextField.setText(text);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JFileChooser c = new JFileChooser();
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            String text = (c.getSelectedFile().getAbsolutePath());
            this.cheminConceptRef1TextField.setText(text);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JFileChooser c = new JFileChooser();
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            String text = (c.getSelectedFile().getAbsolutePath());
            this.cheminConceptRef2TextField.setText(text);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        JFileChooser c = new JFileChooser();
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            String text = (c.getSelectedFile().getAbsolutePath());
            this.cheminTextTestTextField.setText(text);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        JFileChooser c = new JFileChooser();
        int rVal = c.showOpenDialog(this);
        if (rVal == JFileChooser.APPROVE_OPTION)
        {
            String text = (c.getSelectedFile().getAbsolutePath());
            this.cheminTextRefTextField.setText(text);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void executerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executerButtonActionPerformed
        // TODO add your handling code here:

//        Functions.redirectSystemStreams(this.logTextArea);


        System.out.println("Begin");

        double memUsed;
        long beginTime;//millisecondes

        //************* create project *************//
        //
        String projectName = this.nomProjetTextField.getText();
        String projectDir = "../projects/" + projectName + "/";
        String testingOptionsFilePath = projectDir + "testing.xml";
        (new File(projectDir)).mkdirs();
        //
        //************* create project *************//





        //********* training ***********//
        //
        //TrainingOptions
        TrainingOptions[] to = new TrainingOptions[2];
        TrainingOptions.id = projectName;
        //
        //corpus 1
        to[0] = new TrainingOptions();
        to[0].textFile = new File(this.cheminCorpus1TextField.getText());
        to[0].lang = this.langue1ComboBox.getSelectedItem().toString();
        to[0].phraseDelimiter = this.delim1TextField.getText();
        //
        //corpus 2
        to[1] = new TrainingOptions();
        to[1].textFile = new File(this.cheminCorpus2TextField.getText());
        to[1].lang = langue2ComboBox.getSelectedItem().toString();
        to[1].phraseDelimiter = this.delim2TextField.getText();
        //
        //text processing
        TrainingOptions.textCleaner = this.nettoyageApprentissageCheckBox.isSelected();//true
        if (this.nettoyageApprentissageCheckBox.isSelected())
        {
            TrainingOptions.minWordsPhrase = Integer.parseInt(
                    this.phrasesMinAppretissageTextField.getText());
            TrainingOptions.maxWordsPhrase = Integer.parseInt(
                    this.phrasesMaxAppretissageTextField.getText());
        }
        to[0].textFreqMinDeleter = to[1].textFreqMinDeleter = this.frequenceApprentissageCheckBox.isSelected();//true
        if (this.frequenceApprentissageCheckBox.isSelected())
        {
            to[0].minFreqWord = to[1].minFreqWord = Integer.parseInt(
                    this.freqMinApprentissageCheckBox.getText());
            to[0].maxFreqWord = to[1].maxFreqWord = Integer.parseInt(
                    this.freqMaxApprentissageCheckBox.getText());
        }
        to[0].replaceDelim = to[1].replaceDelim = this.normaliseDelimApprentissageCheckBox.isSelected();
        to[0].textLowerCase = to[1].textLowerCase = this.textminisculeApprentissageCheckBox.isSelected();
        to[0].textTokenizer = to[1].textTokenizer = this.tokeniserApprentissageCheckBox.isSelected();
        to[0].textDelimiter = to[1].textDelimiter = false;//false
        to[0].textNotAlphaDeleter = to[1].textNotAlphaDeleter = this.suppMotsNonAlphaApprentissageCheckBox.isSelected();
        to[0].textStopWordsDeleter = to[1].textStopWordsDeleter = this.suppMotsOutilsApprentissageCheckBox.isSelected();
        to[0].textStemmer = to[1].textStemmer = this.stemmersApprentissageCheckBox.isSelected();
        to[0].textLineUnique = to[1].textLineUnique = this.ligneUniqApprentissageCheckBox.isSelected();
        //
        //distances
        TrainingOptions.compareDistancesSrcTrg = false;
        //
        //word,imm,dkl,entropie
        to[0].distancesOrder.add(
                this.metrique1ComboBox.getSelectedItem().toString());//metrique1
        to[1].distancesOrder.add(
                this.metrique2ComboBox.getSelectedItem().toString());//metrique2

        TrainingOptions.bn4Layers = this.utiliserCouchesInterCheckBox.isSelected();//BN as 4 layers
        if (this.utiliserCouchesInterCheckBox.isSelected())
        {
            to[0].distancesOrder.add(
                    this.metriqueCoucheInter1ComboBox.getSelectedItem().toString());//couche1 intermidiaire
            to[1].distancesOrder.add(
                    this.metriqueCoucheInter2ComboBox.getSelectedItem().toString());//couche2 intermidiaire
        }
        //
        //concepts
        TrainingOptions.conceptCountMoyen = Integer.parseInt(
                this.nombreConceptsMoyTextField.getText());
        to[0].splitConceptCount = to[1].splitConceptCount =
                                  Integer.parseInt(
                this.nombreMotsMaxConceptTextField.getText());
        to[0].conceptStemmed = to[1].conceptStemmed = this.conceptsStemmersCheckBox.isSelected();
        to[0].conceptRef = new File(this.cheminConceptRef1TextField.getText());
        to[1].conceptRef = new File(this.cheminConceptRef2TextField.getText());
        //
        //bayes network
        //Methods
        ArrayList<BNLearningOptions> bnLearningOptions = new ArrayList<BNLearningOptions>();
        bnLearningOptions.add(new BNLearningOptions(
                this.structRBComboBox.getSelectedItem().toString(),
                this.scoreRBComboBox.getSelectedItem().toString(),
                Integer.parseInt(this.parentsMaxRBTextField.getText())));
        TrainingOptions.bnLearningOptions = bnLearningOptions;
        //
        ArrayList<ClusteringLearninigOptions> clusteringLearninigOptionses =
                                              new ArrayList<ClusteringLearninigOptions>(); //EuclideanDistance, ManhattanDistance
        clusteringLearninigOptionses.add(new ClusteringLearninigOptions(
                this.methodeClassifComboBox.getSelectedItem().toString(),
                this.distanceClassifComboBox.getSelectedItem().toString()));
        TrainingOptions.clusteringLearninigOptions = clusteringLearninigOptionses;
        //
        //
        //        TrainingOptions.parentBNCount = 2;//
        TrainingOptions.binarytrg = this.coucheBinaireCheckBox.isSelected();//out: words or concepts
        //
        //testingOptionsList
        TestingOptionsList tol = new TestingOptionsList();
        tol.projectDir = projectDir;
        tol.testingOptionsFilePath = testingOptionsFilePath;
        tol.bnClassIndexInit = Integer.parseInt(
                this.classeIndexeRBTextField.getText());//0 ... n
        tol.deleteArcsNoeudClass = this.suppArcsIndexeCheckBox.isSelected();
        tol.alpha = Double.parseDouble(this.alphaRBTextField.getText());
        tol.setEvidence = new boolean[]
        {
            this.setEvidenceRBCheckBox.isSelected()
        };//false
        tol.findInAllwords = new boolean[]
        {
            this.chercheTousMotsRBCheckBox.isSelected()
        };//true
        tol.setEvidenceZero = !this.evidenceEquiRBCheckBox.isSelected();//true
        //
        tol.useBN = this.utiliserRBCheckBox.isSelected();
        tol.useMoses = this.utiliserMosesCheckBox.isSelected();
        tol.ibmModelCount = this.modeleIbmComboBox.getSelectedItem().toString();
        tol.inferenceAllWords = false;//better, always
        //
        System.out.println("Training...");
        if (this.phaseApprentissageCheckBox.isSelected())
        {
            SMTSystem.dataTraining(projectDir,
                                   tol,
                                   to);
        }
        //
        //********* training ***********//


        //********** testing *************//
        //
        System.out.println("Testing...");
        tol = TestingOptionsList.decodeFormFile(testingOptionsFilePath);
        String textInSplit = this.cheminTextTestTextField.getText();
        String textEvalSplit = this.cheminTextRefTextField.getText();
        //text processing
        TrainingOptions.textCleaner = this.nettoyageTestCheckBox.isSelected();//true
        if (this.nettoyageTestCheckBox.isSelected())
        {
            TrainingOptions.minWordsPhrase = Integer.parseInt(
                    this.phrasesMinTestTextField.getText());
            TrainingOptions.maxWordsPhrase = Integer.parseInt(
                    this.phrasesMaxTestTextField.getText());
        }
        to[0].textFreqMinDeleter = to[1].textFreqMinDeleter = this.frequenceTestCheckBox.isSelected();//true
        if (this.frequenceTestCheckBox.isSelected())
        {
            to[0].minFreqWord = to[1].minFreqWord = Integer.parseInt(
                    this.freqMinTestCheckBox.getText());
            to[0].maxFreqWord = to[1].maxFreqWord = Integer.parseInt(
                    this.freqMaxTestCheckBox.getText());
        }
        to[0].replaceDelim = to[1].replaceDelim = this.normaliseDelimTestCheckBox.isSelected();
        to[0].textLowerCase = to[1].textLowerCase = this.textminisculeTestCheckBox.isSelected();
        to[0].textTokenizer = to[1].textTokenizer = this.tokeniserTestCheckBox.isSelected();
        to[0].textNotAlphaDeleter = to[1].textNotAlphaDeleter = this.suppMotsNonAlphaTestCheckBox.isSelected();
        to[0].textStopWordsDeleter = to[1].textStopWordsDeleter = this.suppMotsOutilsTestCheckBox.isSelected();
        to[0].textStemmer = to[1].textStemmer = this.stemmersTestCheckBox.isSelected();
        to[0].textLineUnique = to[1].textLineUnique = this.ligneUniqTestCheckBox.isSelected();
        tol.deleteUnknowenWords = this.suppMotsInconnusTestCheckBox.isSelected();
        to[0].textDelimiter = to[1].textDelimiter = this.phraseDelimTestCheckBox.isSelected();

        memUsed = Functions.getUsedMem();
        beginTime = System.currentTimeMillis();
        //
        SMTSystem.dataTesting(projectDir,
                              projectName,
                              tol,
                              textInSplit,
                              textEvalSplit,
                              to);
        //
        System.out.println((float) (System.currentTimeMillis() - beginTime));
        System.out.println(Functions.getUsedMem() - memUsed);
        //
        //********** testing *************//

        //logs

//        PrintStream out = null;
//        try {
//            out = new PrintStream(new FileOutputStream("output.txt"));
//        } catch (FileNotFoundException ex) {
//            Logger.getLogger(MainFrame2.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        System.setOut(out);
//        ArrayList<String> tetText = new ArrayList<String>(1);
//        tetText.add(System.console().toString());
//        Functions.stringListToFile(tetText, projectDir + "log.txt");
    }//GEN-LAST:event_executerButtonActionPerformed

    private void utiliserCouchesInterCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utiliserCouchesInterCheckBoxActionPerformed
        // TODO add your handling code here:

        if (this.utiliserCouchesInterCheckBox.isSelected())
        {
            this.metriqueCoucheInter1ComboBox.setEnabled(true);
            this.metriqueCoucheInter2ComboBox.setEnabled(true);
        }
        else
        {
            this.metriqueCoucheInter1ComboBox.setEnabled(false);
            this.metriqueCoucheInter2ComboBox.setEnabled(false);
        }
    }//GEN-LAST:event_utiliserCouchesInterCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField alphaRBTextField;
    private javax.swing.JTextField cheminConceptRef1TextField;
    private javax.swing.JTextField cheminConceptRef2TextField;
    private javax.swing.JTextField cheminCorpus1TextField;
    private javax.swing.JTextField cheminCorpus2TextField;
    private javax.swing.JTextField cheminTextRefTextField;
    private javax.swing.JTextField cheminTextTestTextField;
    private javax.swing.JCheckBox chercheTousMotsRBCheckBox;
    private javax.swing.JTextField classeIndexeRBTextField;
    private javax.swing.JCheckBox conceptsStemmersCheckBox;
    private javax.swing.JCheckBox coucheBinaireCheckBox;
    private javax.swing.JTextField delim1TextField;
    private javax.swing.JTextField delim2TextField;
    private javax.swing.JComboBox distanceClassifComboBox;
    private javax.swing.JCheckBox evidenceEquiRBCheckBox;
    private javax.swing.JButton executerButton;
    private javax.swing.JTextField freqMaxApprentissageCheckBox;
    private javax.swing.JTextField freqMaxTestCheckBox;
    private javax.swing.JTextField freqMinApprentissageCheckBox;
    private javax.swing.JTextField freqMinTestCheckBox;
    private javax.swing.JCheckBox frequenceApprentissageCheckBox;
    private javax.swing.JCheckBox frequenceTestCheckBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox langue1ComboBox;
    private javax.swing.JComboBox langue2ComboBox;
    private javax.swing.JCheckBox ligneUniqApprentissageCheckBox;
    private javax.swing.JCheckBox ligneUniqTestCheckBox;
    private javax.swing.JComboBox methodeClassifComboBox;
    private javax.swing.JComboBox metrique1ComboBox;
    private javax.swing.JComboBox metrique2ComboBox;
    private javax.swing.JComboBox metriqueCoucheInter1ComboBox;
    private javax.swing.JComboBox metriqueCoucheInter2ComboBox;
    private javax.swing.JComboBox modeleIbmComboBox;
    private javax.swing.JCheckBox nettoyageApprentissageCheckBox;
    private javax.swing.JCheckBox nettoyageTestCheckBox;
    private javax.swing.JTextField nomProjetTextField;
    private javax.swing.JTextField nombreConceptsMoyTextField;
    private javax.swing.JTextField nombreMotsMaxConceptTextField;
    private javax.swing.JCheckBox normaliseDelimApprentissageCheckBox;
    private javax.swing.JCheckBox normaliseDelimTestCheckBox;
    private javax.swing.JTextField parentsMaxRBTextField;
    private javax.swing.JCheckBox phaseApprentissageCheckBox;
    private javax.swing.JCheckBox phraseDelimTestCheckBox;
    private javax.swing.JTextField phrasesMaxAppretissageTextField;
    private javax.swing.JTextField phrasesMaxTestTextField;
    private javax.swing.JTextField phrasesMinAppretissageTextField;
    private javax.swing.JTextField phrasesMinTestTextField;
    private javax.swing.JComboBox scoreRBComboBox;
    private javax.swing.JCheckBox setEvidenceRBCheckBox;
    private javax.swing.JCheckBox stemmersApprentissageCheckBox;
    private javax.swing.JCheckBox stemmersTestCheckBox;
    private javax.swing.JComboBox structRBComboBox;
    private javax.swing.JCheckBox suppArcsIndexeCheckBox;
    private javax.swing.JCheckBox suppMotsInconnusTestCheckBox;
    private javax.swing.JCheckBox suppMotsNonAlphaApprentissageCheckBox;
    private javax.swing.JCheckBox suppMotsNonAlphaTestCheckBox;
    private javax.swing.JCheckBox suppMotsOutilsApprentissageCheckBox;
    private javax.swing.JCheckBox suppMotsOutilsTestCheckBox;
    private javax.swing.JCheckBox textminisculeApprentissageCheckBox;
    private javax.swing.JCheckBox textminisculeTestCheckBox;
    private javax.swing.JCheckBox tokeniserApprentissageCheckBox;
    private javax.swing.JCheckBox tokeniserTestCheckBox;
    private javax.swing.JCheckBox utiliserCouchesInterCheckBox;
    private javax.swing.JCheckBox utiliserMosesCheckBox;
    private javax.swing.JCheckBox utiliserRBCheckBox;
    // End of variables declaration//GEN-END:variables
}
